# Generated by Django 4.0.3 on 2022-06-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
